### ISSUE TITLE
Invalid module-info.class in asm-repackaged

### ISSUE THREAD

**Issue by llowrey** [eclipse-ee4j/glassfish-hk2#410]
Eclipse has been giving me grief about the module-info.class in asm-repackaged-2.5.0-b62.jar.

When I try to read it with `ModuleDescriptor.read (...)` I get the following

```
Exception in thread "main" java.lang.module.InvalidModuleDescriptorException: Index into constant pool out of range
	at java.base/jdk.internal.module.ModuleInfo.invalidModuleDescriptor(ModuleInfo.java:1092)
	at java.base/jdk.internal.module.ModuleInfo$ConstantPool.checkIndex(ModuleInfo.java:854)
	at java.base/jdk.internal.module.ModuleInfo$ConstantPool.getModuleName(ModuleInfo.java:832)
	at java.base/jdk.internal.module.ModuleInfo.readModuleAttribute(ModuleInfo.java:347)
	at java.base/jdk.internal.module.ModuleInfo.doRead(ModuleInfo.java:253)
	at java.base/jdk.internal.module.ModuleInfo.read(ModuleInfo.java:132)
	at java.base/java.lang.module.ModuleDescriptor.read(ModuleDescriptor.java:2508)
	at net.larko.api.common.test.Foo.main(Foo.java:22)
```

I can read module-info.class from other jars just fine.

My projects running jersey run as expected and so far the only negative consequence is some annoying behavior in eclipse.

java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by Cousjava** [comment]
fixed by #399
