### ISSUE TITLE
module-info.class unreadable by Java 8

### ISSUE THREAD

**Issue by JigarJoshi** [eclipse-ee4j/glassfish-hk2#455]
http://central.maven.org/maven2/org/glassfish/hk2/external/asm-all-repackaged/2.5.0-b42/asm-all-repackaged-2.5.0-b42.jar has all class compiled to language level 8 except for `module-info.class` which is breaking tooling that has to read the class definition.

For example
```

// fails
System.out.println(Class.forName("module-info")); 
        
// works  
System.out.println(Class.forName("org.glassfish.hk2.external.org.objectweb.asm.AnnotationVisitor"));
```

**Comment by romain-grecourt** [comment]
AFAIK `module-info.class` cannot be compiled nor read with 8.

**Comment by JigarJoshi** [comment]
correct - then just avoid packaging it for JAR which is full of classes which are compatible with 8.

**Comment by romain-grecourt** [comment]
If we'd do this, these jars would not be proper java modules.
Duplicating every artifact to support java9 is just not practical.

Any tooling written prior to Java9 that does `Class.forName("module-info")` is broken when running with Java8. Do you have an example of a known tool doing something like this ?

**Comment by JigarJoshi** [comment]
Agreed with you here. I ran into it while building a Java project with `buck`

```
java.lang.ArrayIndexOutOfBoundsException: 32800
	at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3436)
	at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3423)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:722)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:544)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at com.facebook.buck.jvm.java.abi.DirectoryReader.visitClass(DirectoryReader.java:61)
	at com.facebook.buck.jvm.java.abi.JarReader.visitClass(JarReader.java:53)
	at com.facebook.buck.jvm.java.abi.StubJarClassEntry.of(StubJarClassEntry.java:56)
	at com.facebook.buck.jvm.java.abi.StubJarEntry.of(StubJarEntry.java:30)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:102)
	at com.facebook.buck.jvm.java.abi.StubJar.writeTo(StubJar.java:84)
	at com.facebook.buck.jvm.java.CalculateClassAbiStep.execute(CalculateClassAbiStep.java:51)
	at com.facebook.buck.step.StepRunner.runStep(StepRunner.java:54)
```

Line numbers might vary with the source of buck but that is the overall flow where it failed with this artifact was present in classpath.

**Comment by romain-grecourt** [comment]
Isn't that the case that buck uses an older version of ASM and thus is not compatible with Java9+ ?
