### ISSUE TITLE
 Race condition when initializing ClassAnalyzer with CdiInjecteeSkippingClassAnalyzer 

### ISSUE THREAD

**Issue by nhenneaux** [eclipse-ee4j/glassfish-hk2#559]
For now several months, we are getting the following error for some of the builds we execute (I estimate it to 1-5% of all the builds).
It uses Jersey 3.0.2, Weld 4.0.2.Final with Java 16.
The error occurs when executing a JUnit test initializing CDI & JAX-RS server, similar to this test https://github.com/nhenneaux/jersey-httpclient-connector/blob/master/src/test/java/com/github/nhenneaux/jersey/connector/httpclient/JettyServerTest.java#L222 
```
Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAnalyzer(ServiceLocatorImpl.java:2468)
	at org.jvnet.hk2.internal.Utilities.getClassAnalyzer(Utilities.java:143)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:969)
```
I suspect a race condition occurs since the class analyzer uses a HashMap and not a thread safe map (java.util.concurrent.ConcurrentMap). Indeed one CPU core cache could see the map full and another the map empty.
https://github.com/eclipse-ee4j/glassfish-hk2/blob/master/hk2-locator/src/main/java/org/jvnet/hk2/internal/ServiceLocatorImpl.java#L2464

Full stacktrace
```
java.lang.IllegalStateException: jakarta.servlet.ServletException: org.glassfish.jersey.servlet.ServletContainer-f7acce1==org.glassfish.jersey.servlet.ServletContainer@e976386e{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:null,STARTED}
...
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: jakarta.servlet.ServletException: org.glassfish.jersey.servlet.ServletContainer-f7acce1==org.glassfish.jersey.servlet.ServletContainer@e976386e{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:null,STARTED}
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:651)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$2(ServletHandler.java:690)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:714)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:891)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:242)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:469)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
...	... 9 more
Caused by: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:970)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1014)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:207)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$InjectionManagerInjectedCdiTarget.inject(CdiComponentProvider.java:769)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:717)
	at org.jboss.weld.util.ForwardingBeanManager.getReference(ForwardingBeanManager.java:64)
	at org.jboss.weld.bean.builtin.BeanManagerProxy.getReference(BeanManagerProxy.java:87)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiUtil.getBeanReference(CdiUtil.java:129)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier$1.getInstance(AbstractCdiBeanSupplier.java:72)
	at org.glassfish.jersey.ext.cdi1x.internal.AbstractCdiBeanSupplier._provide(AbstractCdiBeanSupplier.java:112)
	at org.glassfish.jersey.ext.cdi1x.internal.GenericCdiBeanSupplier.get(GenericCdiBeanSupplier.java:42)
	at org.glassfish.jersey.inject.hk2.InstanceSupplierFactoryBridge.provide(InstanceSupplierFactoryBridge.java:53)
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2103)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.lambda$getAllServiceHolders$0(AbstractHk2InjectionManager.java:136)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:140)
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:30)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:307)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:151)
	at org.glassfish.jersey.server.internal.inject.ParamExtractorConfigurator.lambda$init$0(ParamExtractorConfigurator.java:49)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:317)
	at org.glassfish.jersey.server.internal.inject.MultivaluedParameterExtractorFactory.get(MultivaluedParameterExtractorFactory.java:68)
	at org.glassfish.jersey.server.internal.inject.AbstractValueParamProvider.get(AbstractValueParamProvider.java:67)
	at org.glassfish.jersey.server.internal.inject.PathParamValueParamProvider.createValueProvider(PathParamValueParamProvider.java:71)
	at org.glassfish.jersey.server.internal.inject.AbstractValueParamProvider.getValueProvider(AbstractValueParamProvider.java:93)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParamValueProvider(ParameterValueHelper.java:148)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.createValueProviders(ParameterValueHelper.java:110)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkValueProviders(ResourceMethodValidator.java:172)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.checkMethod(ResourceMethodValidator.java:81)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitJaxrsResourceMethod(ResourceMethodValidator.java:77)
	at org.glassfish.jersey.server.model.ResourceMethodValidator.visitResourceMethod(ResourceMethodValidator.java:67)
	at org.glassfish.jersey.server.model.ResourceMethod.accept(ResourceMethod.java:876)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:126)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validateWithErrors(ComponentModelValidator.java:132)
	at org.glassfish.jersey.server.model.ComponentModelValidator.access$000(ComponentModelValidator.java:55)
	at org.glassfish.jersey.server.model.ComponentModelValidator$1.run(ComponentModelValidator.java:116)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.server.model.ComponentModelValidator.validate(ComponentModelValidator.java:111)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:366)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:178)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:633)
	... 38 more
Caused by: java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAnalyzer(ServiceLocatorImpl.java:2468)
	at org.jvnet.hk2.internal.Utilities.getClassAnalyzer(Utilities.java:143)
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:969)
	... 110 more

**Comment by nhenneaux** [comment]
#560

**Comment by nhenneaux** [comment]
#560 Merge request trying to fix this issue

**Comment by dmatej** [comment]
Hmm, the referred example uses` jersey-cdi2-se` instead of` jersey-weld2-se` ... btw ... HK2 is nearly a concurrent of Weld, so that really can cause some issues ... it should use just one of them.

Also I see that in service files of cdi1x project is the CdiComponentProvider twice, once as an extension and once as a ComponentProvider impl - that can probably cause redundant initialization too. Or two standalone instances of the same class used as two standalone services ... 

If cpu caches would work like this, nothing would work ever ... prove it (the map is still protected by synchronized methods).

Btw I was digging in my old examples and I found this:

```
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-server</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- If we skip this dependency, jersey-client throws java.lang.IllegalStateException: InjectionManagerFactory not found. -->
        <!-- With that we must have META-INF/beans.xml in src/test/resources -->
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-cdi2-se</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.weld.se</groupId>
            <artifactId>weld-se-core</artifactId>
        </dependency>
```

**Comment by nhenneaux** [comment]
I'm also getting this error while the applications runs in production. It occurred the 11/01/2022 for a service started the 20/12/2021.
I include a truncated stack of the error.
```
jakarta.ws.rs.ProcessingException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer

	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:309) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691) ~[app.jar:x.x.x]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[app.jar:x.x.x]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[app.jar:x.x.x]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[app.jar:x.x.x]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:461) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:329) ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at jdk.proxy2.$Proxy134.partitionKeyCaptureBatchAcquireLock(Unknown Source) ~[?:?]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class [app.jar:x.x.x]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer

	at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65) ~[app.jar:x.x.x]
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:970) ~[app.jar:x.x.x]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1014) ~[app.jar:x.x.x]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:212) ~[app.jar:x.x.x]
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30) ~[app.jar:x.x.x]
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$InjectionManagerInjectedCdiTarget.inject(CdiComponentProvider.java:776) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161) ~[app.jar:x.x.x]
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) ~[app.jar:x.x.x]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:252) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:114) ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at jdk.proxy2.$Proxy177.signature(Unknown Source) ~[?:?]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:144) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:132) ~[app.jar:x.x.x]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297) ~[app.jar:x.x.x]
	... 36 more
Caused by: java.lang.IllegalStateException: Could not find an implementation of ClassAnalyzer with name CdiInjecteeSkippingClassAnalyzer
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAnalyzer(ServiceLocatorImpl.java:2468) ~[app.jar:x.x.x]
	at org.jvnet.hk2.internal.Utilities.getClassAnalyzer(Utilities.java:143) ~[app.jar:x.x.x]
	at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:969) ~[app.jar:x.x.x]
	at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:1014) ~[app.jar:x.x.x]
	at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.inject(AbstractHk2InjectionManager.java:212) ~[app.jar:x.x.x]
	at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.inject(ImmediateHk2InjectionManager.java:30) ~[app.jar:x.x.x]
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$InjectionManagerInjectedCdiTarget.inject(CdiComponentProvider.java:776) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161) ~[app.jar:x.x.x]
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) ~[app.jar:x.x.x]
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.builtin.InstanceImpl.getBeanInstance(InstanceImpl.java:252) ~[app.jar:x.x.x]
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:114) ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at jdk.proxy2.$Proxy177.signature(Unknown Source) ~[?:?]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at internal.class ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:144) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientFilteringStages$RequestFilteringStage.apply(ClientFilteringStages.java:132) ~[app.jar:x.x.x]
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147) ~[app.jar:x.x.x]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297) ~[app.jar:x.x.x]
	... 36 more

**Comment by nhenneaux** [comment]
@dmatej I think I found where the problem lie. It occurs when there is a concurrent initialization from Jersey server but also from each new client. Each new client triggers the initialization of injection which makes things worse.

**Comment by matthjes** [comment]
Hi,
We're getting this error quite suddenly now, first occurrence was May 11th, before this we never saw this error. It's our production environment, we've had no new deployments since mid-April.

Any suggestions how to deal with this?

**Comment by dmatej** [comment]
> Hi, We're getting this error quite suddenly now, first occurrence was May 11th, before this we never saw this error. It's our production environment, we've had no new deployments since mid-April.
> 
> Any suggestions how to deal with this?

With the same version of Jetty, HK2 and Jersey? Could you create a reproducer?

**Comment by nhenneaux** [comment]
The issue is still happening on a regular basis in CI and production with Jersey 3.1.1 & Jetty 11.0.15.

It happens more when the Jersey client is instantiated concurrently.
What about merging MR https://github.com/eclipse-ee4j/glassfish-hk2/pull/560 since it is quite harmless and might fix the issue?

**Comment by avpinchuk** [comment]
@nhenneaux, issue happening in [this](https://github.com/nhenneaux/jersey-httpclient-connector) project too?

**Comment by nhenneaux** [comment]
I don't remember so. It happens when doing concurrent client instantiations and I don't on this project. https://github.com/nhenneaux/jersey-httpclient-connector/blob/master/src/test/java/com/github/nhenneaux/jersey/connector/httpclient/JettyServerTest.java#L412-L413
